### ISSUE TITLE
Issue creating conda environment from conda_environment.yml

### ISSUE THREAD

**Issue by fallonda** [thatchemistryguy/PyParse#3]
fallonda@df-laptop:~/repos/PyParse$ conda env create --name pyparse_env --file conda_environment.yml 
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - intel-openmp==2021.4.0=haa95532_3556
  - brotli==1.0.9=h2bbff1b_7
  - sqlite==3.40.0=h2bbff1b_0
  - pytz==2022.1=py37haa95532_0
  - openssl==1.1.1s=h2bbff1b_0
  - mkl_fft==1.3.1=py37h277e83a_0

**Comment by thatchemistryguy** [comment]
@fallonda Unfortunately I wasn't able to replicate this on my Windows machine (env created and activated successfully), are you able to provide further details?

**Comment by thatchemistryguy** [comment]
@fallonda I've created a mini conda environment containing just the required packages, and adding "--no-deps" when initially creating the env. This environment runs the example_dataset fine, but further testing is probably advisable. Using pip to install seaborn, pandas, matplotlib and rdkit on top of a clean environment is probably recommended.
